### ISSUE TITLE
draw plot 

### ISSUE THREAD

**Issue by zhoudreames** [mrvollger/colored_glass#2]
Hi~，would you tell me how to draw this plot? thanks
![image](https://user-images.githubusercontent.com/54714639/117264888-42881f80-ae86-11eb-9d87-ab59a668b57b.png)

**Comment by zhoudreames** [comment]
I have repeat annonation result,but idont how to draw this ploy,would you tell me ?

**Comment by mrvollger** [comment]
This element of the figure was made by the lead author Glennis Logsdon so you should contact her for details. Though I think it was just a simple R script with ggplot.
